name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle 9.4.0
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 9.4.0

      - name: Gradle version
        shell: pwsh
        run: |
          if (-not (Test-Path "gradle\wrapper\gradle-wrapper.jar")) {
            Write-Host "Wrapper missing — generating..."

            gradle wrapper --gradle-version 9.4.0

            if (-not (Test-Path "gradle\wrapper\gradle-wrapper.jar")) {
              Write-Error "Failed to generate Gradle wrapper"
              exit 1
            }
          } else {
            Write-Host "Wrapper already exists"
          }

      - name: Gradlew version
        run: .\gradlew.bat --version

      - name: Build all versions
        run: .\gradlew.bat buildAll

      - name: Remap all versions
        run: .\gradlew.bat remapAll

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: fabric-mod-builds
          path: "**/build/libs/*.jar"
